service: merafile-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    BUCKET_NAME: mera-upload-dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::mera-upload-dev/*

functions:
  upload:
    handler: functions/handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true

  generateDownloadUrl:
    handler: functions/handler.generateDownloadUrl
    events:
      - http:
          path: download
          method: get
          cors: true

plugins:
  - serverless-offline

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mera-upload-dev
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["GET", "PUT"]
              AllowedOrigins: ["*"]
