service: merafile-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    BUCKET_NAME: mera-upload-dev
    SHORT_LINKS_TABLE: short_links

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::mera-upload-dev/*
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-east-1:738140883213:table/short_links
        - arn:aws:dynamodb:us-east-1:738140883213:table/short_links/index/*

functions:
  upload:
    handler: functions/handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true
          timeout: 30 # seconds, adjust higher if needed

  generateDownloadUrl:
    handler: functions/handler.generateDownloadUrl
    events:
      - http:
          path: download
          method: get
          cors: true

  updateUploadStatus:
    handler: functions/handler.updateUploadStatus
    events:
      - http:
          path: updateUploadStatus
          method: post
          cors: true

  viewFile:
    handler: functions/handler.viewFile
    events:
      - http:
          path: viewFile
          method: get
          cors: true
      - http:
          path: viewFile
          method: options
          cors: true

plugins:
  - serverless-offline

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mera-upload-dev
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["GET", "PUT"]
              AllowedOrigins: ["*"]
